In [1]:
import numpy as np

# Matrix
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix A:\n",A)
print("Matrix B:\n",B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [2]:

# Addition
print("A+B:\n", A+B)

A+B:
 [[ 6  8]
 [10 12]]


In [3]:

# Subtraction
print("A-B:\n",A-B)

A-B:
 [[-4 -4]
 [-4 -4]]


In [6]:

# Multiplication (Matrix product)
print("A x B:\n", np.dot(A,B))

A x B:
 [[19 22]
 [43 50]]


In [7]:

# Transpose
print("Transpose of A:\n",A.T)

Transpose of A:
 [[1 3]
 [2 4]]


In [8]:

# Determinant
print("Determinat of A:",np.linalg.det(A))


Determinat of A: -2.0000000000000004


In [10]:

# Rank
print("Rank of A:",np.linalg.matrix_rank(A))

Rank of A: 2


In [11]:

# Inverse
print("Inverse of A:\n",np.linalg.inv(A))

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
